runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static.*
  static_dir: static
- url: /
  script: main.app
- url: /about
  script: main.app
- url: /gallery
  script: main.app
- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
